### ISSUE TITLE
Performance evaluation

### ISSUE THREAD

**Issue by nyurik** [briannaAndCo/Leaflet.Antimeridian#2]
Hi, thanks for implementing this! It has been a very long standing issue with Leaflet, especially when drawing topojson.  Topojson loosely compresses geojson, which means that even if geojson is perfectly split on the dateline, converting it to topojson often crosses the line, thus creating junk on screen.

My biggest concern is the performance - has this plugin been evaluated in terms of speed?  Have you done any perf evaluations/analysis?

Thanks!!!

**Comment by briannaAndCo** [comment]
I haven't done any performance evaluation so far, although I would expect it to have a minor hit for polylines and a more major hit for polygons.

If you'd like to do some performance testing yourself I'd be very interested in the results!
