### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by emzet** [briannaAndCo/Leaflet.Antimeridian#3]
Hi, thanks for this package, which is very useful, but please publish it to https://www.npmjs.com/, so we can install it through npm. And if it is possible add Typescript typings, too. Thank you.

**Comment by icarter09** [comment]
@briannaAndCo would it be ok for me to publish this plugin to npm? I'm using the Leaflet.Antimeridian plugin on my project and being able to install it through npm would help me out as well. Thanks.

**Comment by m-mohr** [comment]
@icarter09 Did you do that? Otherwise I'd likely do it soon.

**Comment by icarter09** [comment]
@m-mohr I never got around to it. Thanks for picking up on it!

**Comment by m-mohr** [comment]
Thanks for the reminder. Will work on it today or tomorrow.

**Comment by m-mohr** [comment]
I have just published the package to npm, it is named leaflet.antimeridian.

Happy to transfer back the npm module publish rights to the original authors.

**Comment by emzet** [comment]
Here is the link: https://www.npmjs.com/package/leaflet.antimeridian, command for installation is `npm i leaflet.antimeridian`

Closing issue...
